### ISSUE TITLE
use cookies

### ISSUE THREAD

**Issue by Spyna** [Register-it/blog-graphql-server#4]
Abbiamo deciso di non suportare il login, con tutte le menata che ne vengono fuori. 

Però potremo suportare la "gestione degli utenti"  usando i cookies. 

Questo ci permette di usare le subscription "a modo". Perchè quando un utente mette un like o un commento, la subscription lo "ri-spara" anche all'utente stesso. E sul client non c'è verso di capire se "l'ho messo io oppure qualcun altro" e quindi non riesco ad utilizzare le subscription. 

L'idea è quindi che si setti un cookie con scadenza mooolto lunga, in modo da identificare gli utenti

**Comment by pixel13** [comment]
Trattandosi di una demo, penso che possiamo limitarci a gestire i commenti con le subscription: in questo caso è sufficiente controllare l'id del commento per sapere se è quello inserito dall'utente stesso.
