### ISSUE TITLE
add date param to `comments` field on query `posts`

### ISSUE THREAD

**Issue by Spyna** [Register-it/blog-graphql-server#5]
Solo per questioni di demo aggiugnere al field `comments` della query `posts` il parametro opzionale `until` di tipo date, oppure il parametro `first`, in modo da far vedere che è possibile annidiare query nella query

```
query {
  posts (first: 10) {
    nodes {
      date,
      id,
      author {
        image
        displayName
      }
      comments (first: 3, until: "2020-05-31" {
        nodes {
          content
        }
      }
    }
  }
  
}
```

**Comment by pixel13** [comment]
Il server già supporta le query su comments nell'elenco dei post.
